# Generated by Django 5.1.3 on 2024-11-19 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80d516de-7769-42d8-8e32-0e5adced17e8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('702e58cd-9c31-4d59-bd0e-eea59ef27243'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fae59480-44fe-45e6-a307-2502438aab4d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d3c53fa3-e632-4c32-8078-506f0894ad7e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7216b6c-84e5-48e8-bd9e-c7a9cc4d2469'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c83014d-e823-4fc4-b55d-6aa6418b8b3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('82b4b222-aba0-4da8-b2e2-c6640fc023d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
