# Generated by Django 5.1.3 on 2024-12-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='content',
            field=models.TextField(),
        ),
    ]
