# Generated by Django 5.1.3 on 2024-11-19 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c63e5cf-3207-4407-9429-f9759602bc6a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e29bc8a-c6f7-4631-b2a3-93d991c080ee'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('960aee41-1fe6-44ba-80c4-cf621a87d862'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51452cb1-3308-48f9-b5af-763fe969c66d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7de42bcd-6e05-4c31-9468-3b0307615ce5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('767e87b8-8bd4-4393-9291-65032ca14488'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8269f81e-dd2a-4482-8ac7-ac5afcdaf982'), editable=False, primary_key=True, serialize=False),
        ),
    ]
