# Generated by Django 5.1.3 on 2024-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_projectdocument_name_projectdocument_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
