# Generated by Django 5.1.3 on 2024-12-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
