# Generated by Django 5.1.3 on 2024-12-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('open', 'Open'), ('close', 'Close'), ('cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
