# Generated by Django 5.1.3 on 2024-11-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_notification_fcm_token_firebase_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebase_tokens',
            name='fcm_token',
            field=models.CharField(help_text='Token FCM của thiết bị', max_length=255, unique=True),
        ),
    ]
