# Generated by Django 5.1.4 on 2025-01-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_task_actual_hour_task_estimate_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('open', 'Open'), ('close', 'Close'), ('cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
