# Generated by Django 5.1.3 on 2024-11-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_deleted_at_usermodel_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
